image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build

build:
    stage: build
    script:
        - dotnet publish -c release -r win-x64 --self-contained
        - git clone https://gitlab.com/wylieyyyy/hk-service-map.git
        - mv getinfo-csharp/bin/Release/netcoreapp*/win-x64/publish hk-service-map/getinfo
    artifacts:
        paths:
            - "hk-service-map/*"
