image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build

build-exe:
    stage: build
    script:
        - dotnet -c release -r win-x64
    artifacts:
        paths:
            - "getinfo-csharp/bin/Release/netcoreapp*/win-x64/publish/*"
